modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/SamsTheNerd/HexGloop/issues"
showAsResourcePack = false

[[mods]]
modId = "hexgloop"
version = "${mod_version}"
displayName = "Hex Gloop"
displayURL = "https://github.com/SamsTheNerd/HexGloop"
logoFile = "GloopIcon.png"
authors = "samsthenerd"
description = "A very gloopy hex addon"

[[dependencies.hexgloop]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.hexgloop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.hexgloop]]
    modId="architectury"
    mandatory=true
    versionRange="[6.5.82,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hexgloop]]
    modId="hexcasting"
    mandatory=true
    versionRange="[0.10.3,)"
    ordering="NONE"
    side="BOTH"