modid = "hexgloop"
book = "hexcasting:thehexbook"
default_lang = "en_us"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    "{_common.src}/generated/resources",
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
    { modid="hexcasting" },
    { modid="hexdoc" },
]
export_dir = "doc/src/hexdoc_hexgloop/_export/generated"

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex =  { "!Raw"='HexPattern\.fromAngles\("(?P<signature>[qweasd]+)", HexDir\.(?P<startdir>\w+)\),\s*new Identifier\(HexGloop.MOD_ID, "(?P<name>[^"]+)"\)[^;]+?(?:makeConstantOp|Op\w+|Widget\.\w+)(?:[^;]*(?P<is_per_world>true)\);)?' }

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/casting/HexGloopRegisterPatterns.java"
regex = "{^_pattern_regex}"

[minecraft_assets]
# https://github.com/PrismarineJS/minecraft-assets/tree/83e2169afbbce40990d69fc53e5962e4a793d467/data/1.19.1
ref = "83e2169afbbce40990d69fc53e5962e4a793d467"
version = "1.19.1"

[template]
icon = "icon.png"
include = [
    "hexgloop",
    "hexcasting",
    "patchouli",
    "hexdoc",
]

[template.args]
mod_name = "Hex Gloop"
author = "samsthenerd"
show_landing_text = false

# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/com/samsthenerd/hexgloop"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/com/samsthenerd/hexgloop/"

[_forge]
src = "../forge/src"
package = "{src}/main/java/com/samsthenerd/hexgloop/forge"
